### ISSUE TITLE
Multiple bug

### ISSUE THREAD

**Issue by Mozork01** [shizotoaster/thaumon#5]
Hey
Fabric 1.20.1
Fabric Loader 0.14.25

Silverwood Hedge and leaf post not stick 
Silver Wood Wall and Post not stick
Greatwood wall and Post not stick
(maybe it's normal ?)

And research notes visual bug

![2024-01-14_18 27 28](https://github.com/shizotoaster/thaumon/assets/148884018/a9a5af56-79ef-42cc-b6aa-458952e7f6c0)

**Comment by shizotoaster** [comment]
Posts aren't designed to connect (even though they sometimes do). Post model remake is in my to-do list

**Comment by Mozork01** [comment]
I wasn't sure, so I preferred to talk about it. Thank you and good luck
