### ISSUE TITLE
Crash on Dedicated Server

### ISSUE THREAD

**Issue by katubug** [shizotoaster/thaumon#6]
Hi! I added Thaumon to my in-dev modpack, and I'm testing it on a server. Unfortunately, it doesn't seem to be compatible, as I get this crash:

https://pastebin.com/iHZS3ZCU

**Comment by shizotoaster** [comment]
Probably related to a similar crash on Fabric. Will pull a fix asap, thanks for your report!

**Comment by katubug** [comment]
Sure thing! Thanks for the quick response!

**Comment by katubug** [comment]
Hey, any news on this? I am hoping to release my modpack with your mod in it, if possible :) Thanks!

**Comment by shizotoaster** [comment]
The fix is already done and will be a part of 2.2.0-beta which I hope to release by the end of the week

**Comment by shizotoaster** [comment]
I'm sorry the update took so long but it's fixed now. Gonna post the update to modrinth and curse right now
