### ISSUE TITLE
Wood stairs are not craftable

### ISSUE THREAD

**Issue by ZBot9000** [shizotoaster/thaumon#7]
Running 1.20.1 on Fabric/Quilt. Everything else seems fine, but both the greatwood stairs and silverwood stairs don’t have a crafting recipe associated with them. The only way to get them is to add them to inventory through commands or creative.

**Comment by shizotoaster** [comment]
Recipes will get an update (will be remade from scratch) in 2.2.0 beta. I'm going to release it next week, stay tuned
