### ISSUE TITLE
Светлана с днём матери!!!

### ISSUE THREAD

**Issue by tox1cozZ** [shizotoaster/thaumon#8]
С днём рождения!!!
![IMG_20240224_235754_688](https://github.com/shizotoaster/thaumon/assets/7694196/2edaca3a-f6d0-4517-a76c-ced79a71d244)

**Comment by shizotoaster** [comment]
Иди нахуй, долбоеб

**Comment by shizotoaster** [comment]
Closed as not relevant

**Comment by tox1cozZ** [comment]
Света ты больная

**Comment by tox1cozZ** [comment]
![Uploading Screenshot_2024-02-27-18-23-24-34_1c337646f29875672b5a61192b9010f9.jpg…]()

**Comment by tox1cozZ** [comment]
Светлана удали пж я не могу
